// <auto-generated />
namespace web_app_asp_net_mvc_html.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class newversion2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newversion2));
        
        string IMigrationMetadata.Id
        {
            get { return "202110251201257_newversion2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
